export default {
  id: 'refill-inbound',
  label: 'Inbound: Refill request',
  type: 'voice-in',
  direction: 'inbound',
  queue: 'Refill Support',
  patientId: '1',
  script: [
    { at: 0,     do: (ctx) => {} },
    { at: 1800,  do: (ctx) => ctx.connect() },
    { at: 2100,  do: (ctx) => ctx.addIntentTag('Refill') },
    { at: 2400,  do: (ctx) => ctx.transcriptLine('patient', "Hi, I'm calling about my Semaglutide refill. I think I'm running low.") },
    { at: 5000,  do: (ctx) => ctx.transcriptLine('agent', "Of course. Let me pull up your account — I see Semaglutide 2.4mg with three refills remaining.") },
    { at: 7500,  do: (ctx) => ctx.addAutoNote('Refill request: Semaglutide 2.4mg', { id: 'note_refill_1' }) },
    { at: 8200,  do: (ctx) => ctx.addSuggestion({ id: 'sug_refill_action', text: 'Process refill for Semaglutide 2.4mg', category: 'action' }) },
    { at: 9500,  do: (ctx) => ctx.transcriptLine('patient', "Also — my insurance just changed. It's BCBS now.") },
    { at: 12000, do: (ctx) => ctx.addAutoNote('Insurance changed to BCBS', { id: 'note_refill_2' }) },
    { at: 12500, do: (ctx) => ctx.addIntentTag('Insurance') },
    { at: 13000, do: (ctx) => ctx.addSuggestion({ id: 'sug_refill_kb', text: 'Verify prior auth requirements (KB-INS-04)', category: 'kb', kbLink: '/kb/INS-04' }) },
    { at: 14000, do: (ctx) => ctx.confirmNote('note_refill_1') },
    { at: 15000, do: (ctx) => ctx.setSentiment('calm', 0.4, 'improving') },
    { at: 16000, do: (ctx) => ctx.addSuggestion({ id: 'sug_refill_90', text: 'Offer 90-day fill option', category: 'action' }) },
  ],
};
